ignored_colors = []
allowed_colors = ["FFFFFF","000000","FF0000","FF5F1F","FFB463","FDF890","51864D","68AC62","96F88D","244D86","2E62AC","428DF8","7948F7","4F2C96","EF86BA","FEF3EA","D48D66","875A41","737373","EBBDAD","FFCC00","B51A00","CACACA"]
width = 512
height = 570
add-x = 0
add-y = 0
default_prio = 120

[[structure]]
name = "hohenzollern.png"
file = "hohenzollern.png"
disabled = false
startx = 420
starty = 6
priority = 127
overlay_only = true

[[structure]]
name = "reclamheft_new.png"
file = "reclamheft_new.png"
disabled = false
startx = 288
starty = 33
priority = 127
overlay_only = true

[[structure]]
name = "Artemis2_2.png"
file = "Artemis2_2.png"
disabled = false
startx = 350
starty = 6
priority = 127
overlay_only = true

[[structure]]
name = "fax.png"
file = "fax.png"
disabled = false
startx = 154
starty = 28
priority = 127
overlay_only = true

[[structure]]
name = "sdaubner_new.png"
file = "sdaubner_new.png"
disabled = false
startx = 190
starty = 3
priority = 127
overlay_only = true

[[structure]]
name = "marmeladenoma_Haut.png"
file = "marmeladenoma_Haut.png"
disabled = false
startx = 391
starty = 2
priority = 127
overlay_only = true

[[structure]]
name = "fck_nzs_final.png"
file = "fck_nzs_final.png"
disabled = false
startx = 114
starty = 4
priority = 127
overlay_only = true

[[structure]]
name = "Bier_Transparent.png"
file = "Bier_Transparent.png"
disabled = false
startx = 308
starty = 24
priority = 127
overlay_only = true

[[structure]]
name = "Burns_Merz.png"
file = "Burns_Merz.png"
disabled = false
startx = 240
starty = 10
priority = 127
overlay_only = true

[[structure]]
name = "placeLinks.png"
file = "placeLinks.png"
disabled = false
startx = 0
starty = 0
priority = 127
overlay_only = true

[[structure]]
name = "wels_bernd_outline.png"
file = "wels_bernd_outline.png"
disabled = false
startx = 26
starty = 0
priority = 127
overlay_only = true

[[structure]]
name = "Canada_final.png"
file = "Canada_final.png"
disabled = false
startx = 84
starty = 96
priority = 127
overlay_only = true

[[structure]]
name = "weizenglas.png"
file = "weizenglas.png"
disabled = false
startx = 310
starty = 513
priority = 127
overlay_only = true
