ignored_colors = []
allowed_colors = ["FFFFFF","000000","FF0000","FF5F1F","FFB463","FDF890","51864D","68AC62","96F88D","244D86","2E62AC","428DF8","7948F7","4F2C96","EF86BA","FEF3EA","D48D66","875A41","737373","EBBDAD","FFCC00","B51A00","CACACA","BB2F79","52D6FC","2C2C2C"]
width = 512
height = 570
add-x = 0
add-y = 0
default_prio = 120

[[structure]]
name = "curling.png"
file = "curling.png"
disabled = true
startx = 132
starty = 94
priority = 126
overlay_only = true

[[structure]]
name = "hohenzollern.png"
file = "hohenzollern.png"
disabled = true
startx = 420
starty = 6
priority = 127
overlay_only = true

[[structure]]
name = "reclamheft_new.png"
file = "reclamheft_new.png"
disabled = true
startx = 288
starty = 33
priority = 127
overlay_only = true

[[structure]]
name = "Artemis2_2.png"
file = "Artemis2_2.png"
disabled = true
startx = 350
starty = 6
priority = 127
overlay_only = true

[[structure]]
name = "sdaubner_new.png"
file = "sdaubner_new.png"
disabled = true
startx = 190
starty = 3
priority = 127
overlay_only = true

[[structure]]
name = "marmeladenoma_Haut.png"
file = "marmeladenoma_Haut.png"
disabled = true
startx = 391
starty = 2
priority = 127
overlay_only = true

[[structure]]
name = "fck_nzs_final.png"
file = "fck_nzs_final.png"
disabled = false
startx = 115
starty = 4
priority = 127
overlay_only = true

[[structure]]
name = "Burns_Merz.png"
file = "Burns_Merz.png"
disabled = true
startx = 240
starty = 10
priority = 127
overlay_only = true

[[structure]]
name = "wels_bernd_outline.png"
file = "wels_bernd_outline.png"
disabled = true
startx = 26
starty = 0
priority = 127
overlay_only = true

[[structure]]
name = "GrrrOhneBL.png"
file = "GrrrOhneBL.png"
disabled = true
startx = 3
starty = 505
priority = 127
overlay_only = true

[[structure]]
name = "monkeklein.png"
file = "monkeklein.png"
disabled = true
startx = 102
starty = 56
priority = 127
overlay_only = true

[[structure]]
name = "Ado_smol.png"
file = "Ado_smol.png"
disabled = true
startx = 92
starty = 1
priority = 127
overlay_only = true

[[structure]]
name = "durstloscher.png"
file = "durstloscher.png"
disabled = true
startx = 73
starty = 35
priority = 127
overlay_only = true

[[structure]]
name = "Zwieback.png"
file = "Zwieback.png"
disabled = true
startx = 126
starty = 527
priority = 127
overlay_only = true

[[structure]]
name = "fax.png"
file = "fax.png"
disabled = true
startx = 154
starty = 28
priority = 127
overlay_only = true

[[structure]]
name = "GrrrrText.png"
file = "GrrrrText.png"
disabled = true
startx = 0
starty = 548
priority = 127
overlay_only = true

[[structure]]
name = "Ahoi_Brause.png"
file = "Ahoi_Brause.png"
disabled = true
startx = 391
starty = 40
priority = 127
overlay_only = true

[[structure]]
name = "portal_spider.png"
file = "portal_spider.png"
disabled = true
startx = 374
starty = 180
priority = 127
overlay_only = true

[[structure]]
name = "Dino_Nuggis.png"
file = "Dino_Nuggis.png"
disabled = true
startx = 13
starty = 41
priority = 127
overlay_only = true

[[structure]]
name = "wal2.png"
file = "wal2.png"
disabled = true
startx = 1
starty = 19
priority = 127
overlay_only = true

[[structure]]
name = "grill.png"
file = "grill.png"
disabled = true
startx = 293
starty = 542
priority = 127
overlay_only = true

[[structure]]
name = "portal_void.png"
file = "portal_void.png"
disabled = true
startx = 195
starty = 391
priority = 127
overlay_only = true

[[structure]]
name = "Veggie_Wurst.png"
file = "Veggie_Wurst.png"
disabled = true
startx = 260
starty = 512
priority = 127
overlay_only = true

[[structure]]
name = "Spargel3.png"
file = "Spargel3.png"
disabled = true
startx = 248
starty = 544
priority = 127
overlay_only = true

[[structure]]
name = "loon.png"
file = "loon.png"
disabled = true
startx = 439
starty = 344
priority = 127
overlay_only = true

[[structure]]
name = "loonreversed.png"
file = "loonreversed.png"
disabled = true
startx = 406
starty = 344
priority = 127
overlay_only = true

[[structure]]
name = "Kika.png"
file = "Kika.png"
disabled = true
startx = 422
starty = 512
priority = 127
overlay_only = true

[[structure]]
name = "kamellen.png"
file = "kamellen.png"
disabled = true
startx = 422
starty = 530
priority = 127
overlay_only = true

[[structure]]
name = "VC1b.png"
file = "VC1b.png"
disabled = true
startx = 163
starty = 3
priority = 127
overlay_only = true

[[structure]]
name = "Ei2.png"
file = "Ei2.png"
disabled = true
startx = 187
starty = 203
priority = 127
overlay_only = true

[[structure]]
name = "Ei3.png"
file = "Ei3.png"
disabled = true
startx = 319
starty = 150
priority = 127
overlay_only = true

[[structure]]
name = "Ei4.png"
file = "Ei4.png"
disabled = true
startx = 282
starty = 290
priority = 127
overlay_only = true

[[structure]]
name = "Ei5.png"
file = "Ei5.png"
disabled = true
startx = 190
starty = 366
priority = 127
overlay_only = true

[[structure]]
name = "Ei6.png"
file = "Ei6.png"
disabled = true
startx = 504
starty = 175
priority = 127
overlay_only = true

[[structure]]
name = "Ei7.png"
file = "Ei7.png"
disabled = true
startx = 216
starty = 290
priority = 127
overlay_only = true

[[structure]]
name = "Ei8.png"
file = "Ei8.png"
disabled = true
startx = 216
starty = 440
priority = 127
overlay_only = true

[[structure]]
name = "Ei9.png"
file = "Ei9.png"
disabled = true
startx = 327
starty = 266
priority = 127
overlay_only = true

[[structure]]
name = "Ei10.png"
file = "Ei10.png"
disabled = true
startx = 464
starty = 444
priority = 127
overlay_only = true

[[structure]]
name = "Ei11.png"
file = "Ei11.png"
disabled = true
startx = 152
starty = 243
priority = 127
overlay_only = true

[[structure]]
name = "Ei12.png"
file = "Ei12.png"
disabled = true
startx = 80
starty = 411
priority = 127
overlay_only = true

[[structure]]
name = "Ei13.png"
file = "Ei13.png"
disabled = true
startx = 305
starty = 356
priority = 127
overlay_only = true

[[structure]]
name = "Ei14.png"
file = "Ei14.png"
disabled = true
startx = 4
starty = 367
priority = 127
overlay_only = true

[[structure]]
name = "Ei15.png"
file = "Ei15.png"
disabled = true
startx = 236
starty = 124
priority = 127
overlay_only = true

[[structure]]
name = "Ei16.png"
file = "Ei16.png"
disabled = true
startx = 429
starty = 258
priority = 127
overlay_only = true

[[structure]]
name = "Ei17.png"
file = "Ei17.png"
disabled = true
startx = 56
starty = 148
priority = 127
overlay_only = true

[[structure]]
name = "Ei18.png"
file = "Ei18.png"
disabled = true
startx = 466
starty = 224
priority = 127
overlay_only = true

[[structure]]
name = "Ei19.png"
file = "Ei19.png"
disabled = true
startx = 328
starty = 446
priority = 127
overlay_only = true

[[structure]]
name = "Ei20.png"
file = "Ei20.png"
disabled = true
startx = 475
starty = 300
priority = 127
overlay_only = true

[[structure]]
name = "Osterei_de.png"
file = "Osterei_de.png"
disabled = true
startx = 382
starty = 51
priority = 127
overlay_only = true

[[structure]]
name = "Ei1.png"
file = "Ei1.png"
disabled = true
startx = 487
starty = 463
priority = 127
overlay_only = true

[[structure]]
name = "placeLinks.png"
file = "placeLinks.png"
disabled = true
startx = 0
starty = 0
priority = 127
overlay_only = true

[[structure]]
name = "DExCA_hockey.png"
file = "DExCA_hockey.png"
disabled = true
startx = 62
starty = 97
priority = 127
overlay_only = true

[[structure]]
name = "duck_germany.png"
file = "duck_germany.png"
disabled = true
startx = 66
starty = 505
priority = 127
overlay_only = true

[[structure]]
name = "Canada_final_2.png"
file = "Canada_final_2.png"
disabled = true
startx = 84
starty = 96
priority = 127
overlay_only = true

[[structure]]
name = "Aldi_Nord.png"
file = "Aldi_Nord.png"
disabled = true
startx = 478
starty = 9
priority = 127
overlay_only = true

[[structure]]
name = "Aldi_Sud.png"
file = "Aldi_Sud.png"
disabled = true
startx = 226
starty = 510
priority = 127
overlay_only = true

[[structure]]
name = "Paulaner_komplett.png"
file = "Paulaner_komplett.png"
disabled = true
startx = 388
starty = 512
priority = 127
overlay_only = true

[[structure]]
name = "Bierkrake.png"
file = "Bierkrake.png"
disabled = true
startx = 307
starty = 513
priority = 127
overlay_only = true

[[structure]]
name = "Vietnam_new.png"
file = "Vietnam_new.png"
disabled = true
startx = 235
starty = 214
priority = 127
overlay_only = true

[[structure]]
name = "Mehrzweck.png"
file = "Mehrzweck.png"
disabled = true
startx = 50
starty = 513
priority = 127
overlay_only = true

[[structure]]
name = "Bierfass.png"
file = "Bierfass.png"
disabled = true
startx = 310
starty = 30
priority = 127
overlay_only = true

[[structure]]
name = "kleine_Hexe.png"
file = "kleine_Hexe.png"
disabled = true
startx = 93
starty = 533
priority = 127
overlay_only = true

[[structure]]
name = "Bibi_Blocksberg.png"
file = "Bibi_Blocksberg.png"
disabled = true
startx = 61
starty = 535
priority = 127
overlay_only = true

[[structure]]
name = "BassGuitar24.png"
file = "BassGuitar24.png"
disabled = true
startx = 218
starty = 544
priority = 127
overlay_only = true

[[structure]]
name = "swiss_air.png"
file = "swiss_air.png"
disabled = true
startx = 1
starty = 283
priority = 127
overlay_only = true

[[structure]]
name = "indigo2.png"
file = "indigo2.png"
disabled = true
startx = 110
starty = 563
priority = 127
overlay_only = true

[[structure]]
name = "Schoko_Croissant.png"
file = "Schoko_Croissant.png"
disabled = true
startx = 171
starty = 528
priority = 127
overlay_only = true

[[structure]]
name = "ende_whiteborder.png"
file = "ende_whiteborder.png"
disabled = false
startx = 0
starty = 0
priority = 127
overlay_only = true
